//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car_rental_system_website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public double CNIC { get; set; }
        public string ADDRESS { get; set; }
        public string DOB { get; set; }
        public string GENDER { get; set; }
    }
}
