CREATE TABLE [dbo].[Admins]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [NAME] VARCHAR(50) NOT NULL, 
    [PASSWORD] VARCHAR(50) NOT NULL, 
    [CNIC] FLOAT NOT NULL, 
    [ADDRESS] VARCHAR(200) NOT NULL, 
    [DOB] TEXT NOT NULL, 
    [GENDER] VARCHAR(50) NOT NULL
)
