CREATE TABLE [dbo].[CAR]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [IMAGE] IMAGE NOT NULL, 
    [NAME] VARCHAR(50) NOT NULL, 
    [Price] FLOAT NOT NULL, 
    [YEAR] INT NOT NULL, 
    [FUEL] VARCHAR(50) NOT NULL, 
    [TRANSMITION] VARCHAR(50) NOT NULL, 
    [KMDRIVEN] FLOAT NOT NULL
)
