//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car_rental_system_website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string GENDER { get; set; }
        public double CNIC { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
